# Generated by Django 3.2.8 on 2021-11-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211111_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='vendor_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Поставщик'),
        ),
    ]
